name: flutter2js
description: Compiles Flutter apps to Javascript apps.
version: 0.2.0

executables:
  flutter2js: flutter2js

environment:
  sdk: '>=2.0.0-dev.19.0'

dependencies:
  args: '^1.2.0'
  flutter: any
  meta: '^1.1.1'

dev_dependencies:
  test: '^0.12.0'

dependency_overrides:
  flutter:
    git:
      url: https://github.com/flutter2js/flutter2js_packages
      path: packages/flutter
